server:
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sbgnews?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update #当无数据库创建，有数据库时更新
    database: MYSQL #数据库类型
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  profiles:
    active: prod
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
executor:
  default:
    corePoolSize: 10 #核心线程数
    maxPoolSize: 100 #最大线程数
    queueCapacity: 1000 #队列最大长度
    keepAliveSeconds: 300 #线程池维护线程所允许的空闲时间
    threadNamePrefix: defaultAsync- #线程名称前缀